apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-jenkins-eks 
  labels:
    app: app
spec:
  selector:
    matchLabels:
        app: app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: public.ecr.aws/q9j0m8g2/testing:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always