apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-agent-config
data:
  cwagentconfig.json: |
    {
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/myapp.log",
                "log_group_name": "myapp-logs",
                "log_stream_name": "{instance_id}"
              }
            ]
          }
        }
      },
      "metrics": {
        "append_dimensions": {
          "AutoScalingGroupName": "${aws:AutoScalingGroupName}",
          "InstanceId": "${aws:InstanceId}",
          "InstanceType": "${aws:InstanceType}"
        },
        "metrics_collected": {
          "cpu": {
            "measurement": [
              "cpu_usage_idle",
              "cpu_usage_iowait",
              "cpu_usage_user",
              "cpu_usage_system"
            ],
            "metrics_collection_interval": 60,
            "totalcpu": true
          },
          "mem": {
            "measurement": [
              "mem_used_percent"
            ],
            "metrics_collection_interval": 60
          }
        }
      }
    }

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudwatch-agent
spec:
  selector:
    matchLabels:
      name: cloudwatch-agent
  template:
    metadata:
      labels:
        name: cloudwatch-agent
    spec:
      containers:
        - name: cloudwatch-agent
          image: amazon/cloudwatch-agent:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /opt/aws/amazon-cloudwatch-agent/etc/
          env:
            - name: CW_CONFIG_FILE
              value: /opt/aws/amazon-cloudwatch-agent/etc/cwagentconfig.json
          securityContext:
            privileged: true
          resources:
            limits:
              memory: 200Mi
              cpu: 0.5
            requests:
              memory: 200Mi
              cpu: 0.5
      volumes:
        - name: config-volume
          configMap:
            name: cloudwatch-agent-config
            items:
              - key: cwagentconfig.json
                path: cwagentconfig.json
